name: Kafka Spring Boot CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取代码
        uses: actions/checkout@v3

      - name: 设置 Java 环境
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Maven 构建
        run: mvn clean install

      - name: 上传构建产物（.jar）
        uses: actions/upload-artifact@v4
        with:
          name: kafka-demo-jar
          path: target/*.jar